### ISSUE TITLE
cant open mate-disk-usage-analyzer

### ISSUE THREAD

**Issue by stefano-k** [mate-desktop-legacy-archive/Mate-Extra#10]
$ mate-disk-usage-analyzer 

*\* (mate-disk-usage-analyzer:20087): CRITICAL **: Unable to load the user interface file: Apertura del file "/usr/share/baobab/baobab-main-window.ui" non riuscita: File o directory non esistente

**Comment by stefano-k** [comment]
after rebuild, that file is in /usr/share/mate-disk-usage-analyzer.desktop folder

*\* (mate-disk-usage-analyzer:29856): CRITICAL **: Unable to load the user interface file: Apertura del file "/usr/share/mate-disk-usage-analyzer/baobab-main-window.ui" non riuscita: File o directory non esistente

/usr/share/mate-disk-usage-analyzer.desktop/baobab-dialog-scan-props.ui
/usr/share/mate-disk-usage-analyzer.desktop/baobab-main-window.ui

**Comment by perberos** [comment]
done

https://github.com/perberos/Mate-Extra/commit/0b4b91888760c00c47c9039c08505d9e0c487acf
