### ISSUE TITLE
mate-system-tools: gnome conflicting files

### ISSUE THREAD

**Issue by stefano-k** [mate-desktop-legacy-archive/Mate-Extra#11]
/usr/bin/network-admin
/usr/bin/services-admin
/usr/bin/shared-admin
/usr/bin/users-admin
/usr/share/applications/#.desktop
/usr/share/icons/hicolor/#/time-admin.#
/usr/share/omf/#

**Comment by perberos** [comment]
done thanks

https://github.com/perberos/Mate-Extra/commit/ff84789f7b9b553f97fb2aec2b2881e6b1f6150f
https://github.com/perberos/mate-system-tools/commit/d743eef2226ce0ce544c63bb7be5c29fb94d81e7
https://github.com/perberos/mate-system-tools/commit/592d760d086a9dc2a7993915848cc2a7682f4bbd
https://github.com/perberos/mate-system-tools/commit/a6ab10b9920f1b94a36cf65d4af86ea4e0a45405
https://github.com/perberos/mate-system-tools/commit/de2ca050694a2d73c6de9ffcda9bb1d97991c08c
