### ISSUE TITLE
complete renamed version of mate-disk-utility

### ISSUE THREAD

**Issue by raveit65** [mate-desktop-legacy-archive/Mate-Extra#14]
Here is a complete renamed version of mate-disk-utility.
palimpest > matepalimpest
gdu > mdu
with that version i have no conflicts with gnome-disk-utillity in fedora.
Sorry, i can't make a patch because a lot of file names and some folder are renamed.

disadvantage:
/usr/lib64/libgdu.so.0 now called /usr/lib64/libmdu.so.0
gvfs needs /usr/lib64/libgdu.so.0, without this lib no usb-sticks or cdrom-drives are mounted by caja in fedora.
So we need gnome-disk-utility-libs as an dependency for caja.
See issue http://forums.mate-desktop.org/viewtopic.php?f=8&t=31&sid=2d6f8c3d2457a044727b43e37cccabc6
But IHMO is this solution better than conflicts with the package manager, because most people first installed gnome and then mate.
http://dl.dropbox.com/u/49862637/Mate-desktop/mate-disk-utility-2011.12.01.tar.gz

**Comment by stefano-k** [comment]
we removed mate-disk-utility, because we cant maintain it too.
