### ISSUE TITLE
Add PKGBUILD's for mate-utils, mate-system-tools and mate-system-monitor to AUR

### ISSUE THREAD

**Issue by danielgomon** [mate-desktop-legacy-archive/Mate-Extra#2]
Can anyone upload the PKGBUILD's for mate-calc, mate-utils and mate-system-tools to AUR?? It would be nice! 
Source: https://bbs.archlinux.org/viewtopic.php?pid=987509#p987509

Can anyone upload the mate-utils PKGBUILD script to AUR?? It would be really, really nice!!!  
Source: https://bbs.archlinux.org/viewtopic.php?pid=989089#p989089

A binary or PKGBUILD for mate-system-monitor would also be awesome.
Source: https://bbs.archlinux.org/viewtopic.php?pid=987514#p987514

**Comment by Cightline** [comment]
I've added mate-calc to the AUR, although it does not build. It DOES build on my system with a ./configure && make && sudo make install

The build() function throws a error. /bin/install is trying to work on files that are not there. (In the dir bg/)

"/bin/install -c -m 644 C/legal.xml /tmp/yaourt-tmp-root/aur-mate-calc/pkg/usr/share/mate/help/gcalctool/C/legal.xml" _Good_

But it then moves on to a folder called "bg/" which I believe is just another translation. 

"/bin/install: cannot stat `./bg/legal.xml': No such file or directory"
_Obviously bad_

Maybe Perberos knows what's going on. Its probably a incorrect var.

**Comment by perberos** [comment]
Thank you for the tips.

I fixed with
https://github.com/Perberos/Mate-Extra/commit/af8a6ec939f0ab52c366b71fb99a6a499d1641f5
and
https://github.com/Perberos/Mate-Extra/commit/9ffdf002170cf55471b38e4a12f425848934a651

**Comment by perberos** [comment]
button fail

**Comment by Cightline** [comment]
mate-calc in AUR works

**Comment by danielgomon** [comment]
Any news??

**Comment by perberos** [comment]
Quest Complete
