### ISSUE TITLE
mate-image-viewer python configuration error (ubuntu build script)

### ISSUE THREAD

**Issue by apcro** [mate-desktop-legacy-archive/Mate-Extra#4]
The configure script for `mate-image-viewer` fails on python version detection:

```
checking whether Python support is requested... autodetect
checking whether /usr/bin/python2 version >= 2.3... configure: error: too old
cro@shiny:~/Workspace/Mate-Extra/mate-image-viewer$ which python
/usr/bin/python
cro@shiny:~/Workspace/Mate-Extra/mate-image-viewer$ /usr/bin/python --version
Python 2.7.2+
cro@shiny:~/Workspace/Mate-Extra/mate-image-viewer$
```

The script in `distros/ubuntu/build` sets `PYTHON=/usr/bin/python2` but `which python` returns `/usr/bin/python`.

Changing the script to `PYTHON=/usr/bin/python` allows the configuration and build to complete.

**Comment by perberos** [comment]
sorry, thanks

https://github.com/Perberos/Mate-Extra/commit/14ea3f05166c9356e2a9fb613c9ef7c7b032c7ec
