### ISSUE TITLE
mate-applets

### ISSUE THREAD

**Issue by apcro** [mate-desktop-legacy-archive/Mate-Extra#5]
mate-applets depends on `gstreamer0.10-base-plugins` if --enable-mixer is used, however this library doesn't exist. `gstreamer0.10-plugins-base` does exist however.

**Comment by szesch** [comment]
What distro are you using? Are you building from source taken from git, sourceforge, or something else?

**Comment by apcro** [comment]
I've resolved this issue. I was attempting to compile it from git source (not the downloaded tarball) and a recent update has resolved the dependency issue. I've now managed to properly compile the entire package from git source, including the mixer applet.

There's still an issue with the trashapplet and cpufreq applets not appearing when you add them to the panel though.
