### ISSUE TITLE
mate-media error in configure

### ISSUE THREAD

**Issue by stefano-k** [mate-desktop-legacy-archive/Mate-Extra#8]
config.status: creating mate-volume-control/data/mate-volume-control.desktop.in
config.status: creating mate-volume-control/data/icons/Makefile
config.status: creating mate-volume-control/data/icons/16x16/Makefile
config.status: error: cannot find input file: `mate-volume-control/data/icons/16x16/apps/Makefile.in'
make: **\* [debian/stamp-autotools] Error 1

**Comment by perberos** [comment]
use autogen.sh

https://github.com/perberos/Mate-Extra/commit/60d526c3f1714db6e6f029e650c8aeb810cf4368

**Comment by stefano-k** [comment]
done
