### ISSUE TITLE
error compiling mate-utils

### ISSUE THREAD

**Issue by stefano-k** [mate-desktop-legacy-archive/Mate-Extra#9]
baobab-chart.c:978:21: warning: variable 'class' set but not used [-Wunused-but-set-variable]
  CC    mate_disk_usage_analyzer-baobab-treemap.o
  LINK  mate-disk-usage-analyzer
make[4]: Leaving directory `/tmp/buildd/mate-utils-1.0.6/baobab/src'
Making all in data
make[4]: Entering directory`/tmp/buildd/mate-utils-1.0.6/baobab/data'
make[4]: **\* No rule to make target `mate-disk-usage-analyzer.desktop.in.in', needed by`mate-disk-usage-analyzer.desktop.in'.  Stop.
make[4]: Leaving directory `/tmp/buildd/mate-utils-1.0.6/baobab/data'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory`/tmp/buildd/mate-utils-1.0.6/baobab'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/tmp/buildd/mate-utils-1.0.6'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/tmp/buildd/mate-utils-1.0.6'
make: **\* [debian/stamp-makefile-build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by perberos** [comment]
done, thanks

https://github.com/perberos/Mate-Extra/commit/59414df7561bee9325f7efc065fc2794fe6cec06

**Comment by stefano-k** [comment]
solved, thanks :)
